      - name: Guardar cambios automáticamente
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Actualización automática: datos y reportes"
          branch: main
          commit_user_name: "AndresParra0916"
          commit_user_email: "AndresParra0916@users.noreply.github.com"
